config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'travels#index'

  resources :travels, only: %i[new create show index]
  resources :categories, only: %i[new create show index]
  resources :comments, only: [:create]
  resources :votes, only: %i[new create]
  resources :users, only: %i[new create]
  resources :sessions, only: %i[new create destroy]

  get 'sign_up', to: 'users#new', as: 'sign_up'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :travel
  validates :author_name, presence: true, length: { minimum: 6 }
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)

    @comment.save

    redirect_to travel_path(@comment.travel_id)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body, :travel_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def show_ask_author(form)
    html = ''
    html += '<p>'

    if current_user.nil?
      html += form.label :author_name, 'Your Name:'
      html += '<br>'
      html += form.text_field :author_name, class: 'form-control'
    else
      html += form.label :author_name, "Your Name: #{current_user.name}"
      html += form.hidden_field :author_name, value: current_user.name
    end
    html += '</p>'
    html.html_safe
  end
end

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for :comment, :url => comments_path(@comment.travel_id) do |f| %>
  <p>
    <%= f.hidden_field :travel_id %>
  </p>

  <%= show_ask_author(f) %>
  
  <p>
    <%= f.label :body, "Your Comment:" %><br/>
    <%= f.text_area :body, class: 'form-control' %>
  </p>
  <p>
    <%= f.submit 'Submit', class:'btn btn-lg btn-primary btn-block mt-3' %>
  </p>
<% end %>